site_name: CARMA Platform
repo_name: usdot-fhwa-stol/carma-platform
repo_url: https://github.com/usdot-fhwa-stol/carma-platform

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - monorepo
  - search

theme:
  features:
    - navigation.indexes
    - navigation.top
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
    - scheme: default
      primary: amber
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

nav:
  - Overview: "index.md"
  - Getting started:
      - "getting_started/index.md"
  - Perception:
      - "perception/index.md"
      - CARMA cooperative perception: "!include ./carma_cooperative_perception/mkdocs.yaml"
  - Guidance:
      - "guidance/index.md"
  - Hardware interface:
      - "hardware_interface/index.md"
  - Localization:
      - "localization/index.md"
  - Messaging:
      - "messaging/index.md"
